swagger: '2.0'
info:
  title: Sanguis API
  version: '0.1'
paths:
  /bloodstations:
    get:
      produces:
        - application/json
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/BloodStation'
definitions:
  BloodStation:
    type: object
    required:
      - name
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
        example: Центр крови ФМБА России
